package com.epam.training.provider.command;

public enum CommandName {
	ADD_PAYMENT,
	ADD_TARIFF, 
	BUY_TARIFF,
	DELETE_TARIFF, 
	DISPLAY_TARIFFS, 
	DISPLAY_USERS, 
	EDIT_TARIFF, 
	REGISTRATION,
	SEARCH_ONE_TARIFF,
	SEARCH_TARIFFS, 
	SEARCH_USER_PAYMENTS,
	SHOW_ADMIN_PAGE,
	SHOW_INDEX_PAGE, 
	SHOW_USER_PAGE,
	SHOW_USER_TARIFFS,
	SIGN_IN, 
	SIGN_OUT, 
	WRONG_REQUEST;
}
