package com.epam.training.provider.command;

public enum CommandName {
	INDEX, SIGN_IN, SIGN_OUT, REGISTRATION, ALL_TARIFFS, WRONG_REQUEST, TARIFFS, CARD_TARIFF, EDIT_TARIFF, ADD_TARIFF, DELETE_TARIFF, USERS, PAY_ACT, REFILL, 
	USER_MAIN, ADMIN_MAIN;
}
